app:
  name: "URL Shortener"
  version: "1.0.0"

server:
  host: "shortener"
  port: 8081
  shutdown_timeout: 10s

db:
  postgres:
    host: ${DB_POSTGRES_HOST}
    port: 5432
    username: ${DB_POSTGRES_USERNAME}
    password: ${DB_POSTGRES_PASSWORD}
    database: ${DB_POSTGRES_DATABASE}
    max_open_conns: 0
    max_idle_conns: 2
    conn_max_lifetime: 0s

redis:
  host: "redis"
  port: 6379
  password: ""
  database: 0
  ttl: 1h

logger:
  level: "info"

gin:
  mode: "release"
