basePath: /
definitions:
  models.AnAgregation:
    properties:
      day_count:
        additionalProperties:
          type: integer
        type: object
      month_count:
        additionalProperties:
          type: integer
        type: object
      short_url:
        type: string
      total_count:
        type: integer
      user_agent_count:
        additionalProperties:
          type: integer
        type: object
    type: object
  request.CreateShortURLRequest:
    properties:
      short_url:
        type: string
      url:
        type: string
    required:
    - url
    type: object
  response.CreateShortURLResponse:
    properties:
      id:
        type: integer
      short_url:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API for URL Shortener
  termsOfService: http://swagger.io/terms/
  title: URL Shortener
  version: "1.0"
paths:
  /api/v1/analytics/{short_url}:
    get:
      description: get analytics by provided short url
      parameters:
      - description: short url
        in: path
        name: short_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AnAgregation'
        "400":
          description: invalid short url
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: get analytics by short url
      tags:
      - ANALYTICS API
  /api/v1/s/{short_url}:
    get:
      description: redirect to original url by provided short url
      parameters:
      - description: short url
        in: path
        name: short_url
        required: true
        type: string
      produces:
      - application/json
      - text/plain
      - text/html
      responses:
        "302":
          description: redirect by short url
          headers:
            Location:
              description: redirect URL
              type: string
        "400":
          description: invalid short url
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: provided short url does not exist
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: redirect by short url
      tags:
      - URL API
  /api/v1/shorten:
    post:
      consumes:
      - application/json
      description: create short url with provided params
      parameters:
      - description: create short url request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateShortURLRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CreateShortURLResponse'
        "400":
          description: validate error
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: conflict error
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: create short url
      tags:
      - URL API
swagger: "2.0"
